name: Deploy to testflight
on:
  push:
    branches:
      - master
jobs:
  deploy-to-testflight:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸš€ Build app
        run: eas build --platform ios --profile production --non-interactive

      - name: ğŸš€ Submit app
        run: eas submit --platform ios --latest --non-interactive

      - name: Get last build number
        id: last_build_number
        run: |
          echo ::set-output name=build_number::$(sed -nE 's/.*"buildNumber": "([0-9]+)".*/\1/p' app.json)

      - name: ğŸ” Update Build Number
        run: |
          new_build_number=$(( ${{ steps.last_build_number.outputs.build_number }} + 1 ))
          sed -i "s/\"buildNumber\": \"[^\"]*\"/\"buildNumber\": \"$new_build_number\"/g" app.json
          git config --global user.email "abhishek@wednesday.is"
          git config --global user.name "Abhishek Mishra"
          git commit -am "Bumpup build number"
          git push
